name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "build && push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - name: node | ${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm test

      