name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "build && push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - name: node | ${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm test  

      - name: Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker image
        run: docker build -t caul11/ci:${{steps.generate_tag.outputs.sha}} .

      - name: Push image
        run: docker push caul11/ci:${{steps.generate_tag.outputs.sha}}
